# gpt-toy-config.yaml
#   Toy GPT-2 Config, currently working with the WikiText-103 Dataset, GPT-2 Small Architecture, and Single-Node
#   Trainer. Inheritance and core paths can all be overridden from the command line or by re-writing these files.
---
# Inherit Dataset, Tokenization, Model, and Training Details
inherit:
    - datasets/wikitext103.yaml
    - models/gpt2-small.yaml
    - trainers/toy.yaml

# Run ID -- defaults to `null`; override as you like!
run_id: null

# Weights & Biases (Set os.environ["WANDB_PROJECT"])
wandb: mistral-debugging
group: null

# Artifacts & Caching
artifacts:
    cache_dir: /u/scr/nlp/mercury/mistral/artifacts
    run_dir: /u/scr/nlp/mercury/mistral/runs

# Save Effective Batch Size for Easy Handling ==> Main Code asserts infra + training_config results in this!
bsz: 8

# Resume from Checkpoint
resume: false

# `torch.distributed` Default Infra Parameters -- to be overwritten by call to `torch.distributed.launch`
local_rank: -1
nnodes: 1
nproc_per_node: 8

# DeepSpeed Default Infra Parameters -- to be overwritten by call to `DeepSpeed`
num_gpus: 8
num_nodes: 1
world_size: 8

# Logging Parameters -- 10 = DEBUG, 20 = INFO, 30 = WARNING, 40 = ERROR, 50 = CRITICAL
log_level: 20

# Random Seed
seed: 21
