
name: Run Tests
on: [push]
jobs:
  Run-Mistral-Tests:
    runs-on: self-hosted
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Setting up Conda Environment
        run: |
          echo "Setting up conda env for this test!"
          eval "$(conda 'shell.bash' 'hook' 2>/dev/null)" # make conda happy
          bash setup/setup.sh mistral-${{github.sha}} 
          conda activate mistral-${{github.sha}}
      - name: Installing test dependencies
        run: |
          eval "$(conda 'shell.bash' 'hook' 2>/dev/null)" # make conda happy
          conda activate mistral-${{github.sha}}
          pip install -r setup/test-requirements.txt
      - name: Setting up environment variables
        run: |
          echo 'Deactivating wandb'
          eval "$(conda 'shell.bash' 'hook' 2>/dev/null)" # make conda happy
          conda activate mistral-${{github.sha}}
          cd tests ; wandb disabled
          echo 'MISTRAL_TEST_DIR:'
          echo $MISTRAL_TEST_DIR
      - name: Run tests (single node/single GPU)
        run: |
          eval "$(conda 'shell.bash' 'hook' 2>/dev/null)" # make conda happy
          conda activate mistral-${{github.sha}}
          cd tests
          echo 'Clearing artifacts'
          rm -rf $MISTRAL_TEST_DIR/artifacts
          CUDA_VISIBLE_DEVICES=0 pytest --durations=0
      - name: Run tests (Deepspeed 2xGPUs)
        run: | 
          eval "$(conda 'shell.bash' 'hook' 2>/dev/null)" # make conda happy
          conda activate mistral-${{github.sha}}
          export PYTHONPATH=${GITHUB_WORKSPACE}
          cd tests
          echo 'Clearing artifacts'
          rm -rf $MISTRAL_TEST_DIR/artifacts
          python run_deepspeed_tests.py
      - name: Delete conda environment
        if: always()
        run: |
          eval "$(conda 'shell.bash' 'hook' 2>/dev/null)" # make conda happy
          conda deactivate
          conda env remove -n mistral-${{github.sha}}
      - run: echo "All tests finished!"
      - run: echo "ğŸ This job's status is ${{ job.status }}."
