
name: Run Tests
on: [push]
jobs:
  Run-Mistral-Tests:
    runs-on: self-hosted
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Setup
        run: |
          cp -r /home/stanzabuild/mistral/wandb .
          wandb offline
      - name: Tests for arguments (single node/single GPU)
        run: |
          cd tests
          CUDA_VISIBLE_DEVICES=0 pytest test_args.py
      - name: Tests for checkpoints (single node/single GPU)
        run: |
          cd tests
          CUDA_VISIBLE_DEVICES=0 pytest test_checkpoint.py
      - name: Tests for upcasting (single node/single GPU)
        run: |
          cd tests
          CUDA_VISIBLE_DEVICES=0 pytest test_fp.py
      - name: Tests for random seed (single node/single GPU)
        run: |
          cd tests
          CUDA_VISIBLE_DEVICES=0 pytest test_seed.py
      - run: echo "ğŸ This job's status is ${{ job.status }}."
