
name: Run Tests
on: [push]
jobs:
  Run-Mistral-Tests:
    runs-on: self-hosted
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Setup
        run: |
          echo 'Deactivating wandb'
          cd tests ; wandb disabled
          echo 'MISTRAL_TEST_DIR:'
          echo $MISTRAL_TEST_DIR
      - name: Run tests (single node/single GPU)
        if: always()
        run: |
          cd tests
          CUDA_VISIBLE_DEVICES=0 pytest --durations=0
      - run: echo "All tests finished!"
      - run: echo "ğŸ This job's status is ${{ job.status }}."
